version: "2.1"
services:
  hackbox:
    image: rodfer0x80/hackbox:latest
    container_name: rodfer0x80/hackbox:latest
    user: 1000:1000
    volumes:
      - ./opt:/root/run
    ports:
      - 1337:1337
    restart: unless-stopped
    entrypoint: ./run.sh
